### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by kFxDaKing** [r3ps4J/r3_pawnshop#1]
**Feature request**

Possibility to choose which money i get for certain item, so i can sell other things here too.

**Example:**

`Config.PawnshopItems = {
	weapon_piece = 2500, - cash
	bones = 120, -cash
	nuts_and_bolts = 80, -cash
	gold_ring = 1250, -cash
	metalscrap = 50, -black_money
        weed = 50, -black_money

}`

**Comment by ablehdexter** [comment]
this can't sell weapons, pls update
